#### https://asecuritysite.com/encryption/mce_k 
#### http://www-math.ucdenver.edu/~wcherowi/courses/m5410/ctcmcel.html
#### https://medium.com/asecuritysite-when-bob-met-alice/a-practical-example-for-mceliece-cryptography-779bec96ef9d
#### Decimal to binary conversion https://www.rapidtables.com/convert/number/decimal-to-binary.html

In [1]:
import numpy
import sys
import io
G =numpy.array([[1,0,0,0,1,1,1],[0,1,0,0,0,1,1],[0,0,1,0,1,0,1],[0,0,0,1,1,1,0]])
H =numpy.array([[1,0,0,0,1,1,1],[0,1,0,1,0,1,1],[0,0,1,1,1,0,1]])
S =numpy.array([[1,1,0,1],[1,0,0,1],[0,1,1,1],[1,1,0,0]])
P =numpy.array([[0,1,0,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,0,0,1],[1,0,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,0,0,1,0],[0,0,0,0,1,0,0]])	
#P = numpy.identity(7, dtype = int)

mapping=([4,1,5,2,7,6,3])

matrix = numpy.dot(S,G)%2
G_1 = numpy.dot(matrix,P)%2

message1 = ([1,1,0,0])
e = ([0,0,0,0,1,0,0])

'''
if (len(sys.argv)>1):
        message=numpy.genfromtxt(io.StringIO(sys.argv[1]),delimiter=',')
'''
print('Message1:\n',message1, 'In decimal format: ', int(''.join(map(str,message1)),2))
print('G:\n',G)
print('S:\n',S)
print('P:\n',P)
print('Result (GSP):\n',G_1)

res=numpy.dot(message1,G_1)%2

cipher1 = numpy.add(res,e)%2

print('\nCipher1:',cipher1, 'In decimal format: ', int(''.join(map(str,cipher1)),2))

P_1=numpy.linalg.inv(P)%2

print('\nP^{-1}:\n',P_1)

y1_1 = numpy.dot(cipher1,P_1)%2

syndrome = numpy.dot(H,numpy.transpose(cipher1))%2

error = syndrome[0]+2*syndrome[1]+4*syndrome[2]
print("\nsyndrome\':",syndrome,error)
error=mapping[int(error-1)]
print ("Error position: ",error)
print ("y': ",y1_1)
y1_1[error-1]=(y1_1[error-1]+1)%2
print ("y' (corrected): ",y1_1)

S_1=numpy.linalg.inv(S)%2

print ('\nS^{-1}:\n',S_1)

# syn = ([1,0,0,0])

decipher = numpy.dot(y1_1[0:4],S_1)%2

print ('\nDecipher:',decipher, 'In decimal format: ', int(''.join(map(str,[int(i) for i in decipher])),2))

Message1:
 [1, 1, 0, 0] In decimal format:  12
G:
 [[1 0 0 0 1 1 1]
 [0 1 0 0 0 1 1]
 [0 0 1 0 1 0 1]
 [0 0 0 1 1 1 0]]
S:
 [[1 1 0 1]
 [1 0 0 1]
 [0 1 1 1]
 [1 1 0 0]]
P:
 [[0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0]]
Result (GSP):
 [[1 1 0 1 0 1 0]
 [1 1 0 0 1 0 0]
 [1 0 0 1 0 0 1]
 [0 1 1 1 0 0 0]]

Cipher1: [0 0 0 1 0 1 0] In decimal format:  10

P^{-1}:
 [[0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]

syndrome': [1 0 1] 5
Error position:  7
y':  [0. 1. 0. 0. 0. 1. 0.]
y' (corrected):  [0. 1. 0. 0. 0. 1. 1.]

S^{-1}:
 [[1. 1. 0. 1.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]
 [1. 0. 0. 1.]]

Decipher: [1. 1. 0. 0.] In decimal format:  12


#### Making S and P as identity matrix. This will tunr Mceliece into symmentric key cryptography. 
#### never the less, this can be transformed into asymmetric by doing singular value decomposition to G matric.
#### Specifically, the singular value decomposition of an  m\times n complex matrix M is a factorization of the form 
#### {M} =U\Sigma V^{*}, where U is an m\times m complex unitary matrix, \Sigma is an m\times n rectangular diagonal matrix 
####    with non-negative real numbers on the diagonal, and V is an n\times n complex unitary matrix.
#### In this case, U, \sigma, V are the secret keys and G is the public key
#### Paper title could be: FPGA Design to employ McEclience cryptography on decision tree. OR Secure computing of decision tree on FPGA using Mceliece cryptography.

In [2]:
codes = {}
message = [([0,0,0,0]), ([0,0,0,1]), ([0,0,1,0]), ([0,0,1,1]), ([0,1,0,0]), ([0,1,0,1]), ([0,1,1,0]), ([0,1,1,1]), 
           ([1,0,0,0]), ([1,0,0,1]), ([1,0,1,0]), ([1,0,1,1]), ([1,1,0,0]), ([1,1,0,1]), ([1,1,1,0]), ([1,1,1,1])]
e = ([0,0,0,0,1,0,0])
print(f'G = {G}')
for message1 in message:
    cipher1=numpy.dot(message1,G)%2
    cipher1 = numpy.add(cipher1,e)%2
    print('\n Message=' , int(''.join(map(str,message1)),2), 'Cipher1:',cipher1, 'In decimal format: ', int(''.join(map(str,cipher1)),2))
    #print('\nCipher1:',cipher1)
    codes[int(''.join(map(str,message1)),2)] = int(''.join(map(str,cipher1)),2)    

G = [[1 0 0 0 1 1 1]
 [0 1 0 0 0 1 1]
 [0 0 1 0 1 0 1]
 [0 0 0 1 1 1 0]]

 Message= 0 Cipher1: [0 0 0 0 1 0 0] In decimal format:  4

 Message= 1 Cipher1: [0 0 0 1 0 1 0] In decimal format:  10

 Message= 2 Cipher1: [0 0 1 0 0 0 1] In decimal format:  17

 Message= 3 Cipher1: [0 0 1 1 1 1 1] In decimal format:  31

 Message= 4 Cipher1: [0 1 0 0 1 1 1] In decimal format:  39

 Message= 5 Cipher1: [0 1 0 1 0 0 1] In decimal format:  41

 Message= 6 Cipher1: [0 1 1 0 0 1 0] In decimal format:  50

 Message= 7 Cipher1: [0 1 1 1 1 0 0] In decimal format:  60

 Message= 8 Cipher1: [1 0 0 0 0 1 1] In decimal format:  67

 Message= 9 Cipher1: [1 0 0 1 1 0 1] In decimal format:  77

 Message= 10 Cipher1: [1 0 1 0 1 1 0] In decimal format:  86

 Message= 11 Cipher1: [1 0 1 1 0 0 0] In decimal format:  88

 Message= 12 Cipher1: [1 1 0 0 0 0 0] In decimal format:  96

 Message= 13 Cipher1: [1 1 0 1 1 1 0] In decimal format:  110

 Message= 14 Cipher1: [1 1 1 0 1 0 1] In decimal format:  117

 Mess

#### Inequality preserving homomorphic encrytion instead of additive or multiplicative homommorphic encryption.
#### Unlike NTRU where key size is large and then NTRU variant to make it additive homomoprrhic, then doing comprssion to 
#### make it light weight and run on FPGA
#### In our McEliece approach, we start with smaller key size to have secure codes and then develop lightweight crypto mechanims
#### so that it is easilty implementable on FPGA. 
#### The cipher size could be increased by adding random values between ciphers for obfuscation. 
#### Security could be increased by increasing the secure codes. currently it has only 16 codes. (More search is required to have goppa codes with large value of m, n, t.)

#### NTRU variant was showing additive homomorphic but such property is not required for decision tree. The inequality preserving property
#### is sufficient to have encrypted decision tree implementation.

#### The generation equation to maintain order-preserving encrytion is ;
#### message1 x G_matrix > message2 x G_matrix if message1 > message2. What is such G_matrix provided that message is recoverable from (message x G_matrix + error)

In [13]:
#MNIST pixels
cipher={}
for i in range(255):
    print(f'message = {i}. Representation: {int(i / 15)}*15+{i % 15}.  Cipher = {codes[int(i/16)], codes[i%16]}.')
    cipher[i] = (codes[int(i/16)], codes[i%16])

message = 0. Representation: 0*15+0.  Cipher = (4, 4).
message = 1. Representation: 0*15+1.  Cipher = (4, 10).
message = 2. Representation: 0*15+2.  Cipher = (4, 17).
message = 3. Representation: 0*15+3.  Cipher = (4, 31).
message = 4. Representation: 0*15+4.  Cipher = (4, 39).
message = 5. Representation: 0*15+5.  Cipher = (4, 41).
message = 6. Representation: 0*15+6.  Cipher = (4, 50).
message = 7. Representation: 0*15+7.  Cipher = (4, 60).
message = 8. Representation: 0*15+8.  Cipher = (4, 67).
message = 9. Representation: 0*15+9.  Cipher = (4, 77).
message = 10. Representation: 0*15+10.  Cipher = (4, 86).
message = 11. Representation: 0*15+11.  Cipher = (4, 88).
message = 12. Representation: 0*15+12.  Cipher = (4, 96).
message = 13. Representation: 0*15+13.  Cipher = (4, 110).
message = 14. Representation: 0*15+14.  Cipher = (4, 117).
message = 15. Representation: 1*15+0.  Cipher = (4, 123).
message = 16. Representation: 1*15+1.  Cipher = (10, 4).
message = 17. Representation: 1*15

###### Concatenating the cipher components to build a cipher that goes into the verilog code.

In [14]:
ciphertext = {}
for i in range(255):
    ciphertext[i] = '0b' + format(cipher[i][0],'08b') + format(cipher[i][1],'08b')
    ciphertext[i] = int(ciphertext[i], 2)
print(ciphertext)   

{0: 1028, 1: 1034, 2: 1041, 3: 1055, 4: 1063, 5: 1065, 6: 1074, 7: 1084, 8: 1091, 9: 1101, 10: 1110, 11: 1112, 12: 1120, 13: 1134, 14: 1141, 15: 1147, 16: 2564, 17: 2570, 18: 2577, 19: 2591, 20: 2599, 21: 2601, 22: 2610, 23: 2620, 24: 2627, 25: 2637, 26: 2646, 27: 2648, 28: 2656, 29: 2670, 30: 2677, 31: 2683, 32: 4356, 33: 4362, 34: 4369, 35: 4383, 36: 4391, 37: 4393, 38: 4402, 39: 4412, 40: 4419, 41: 4429, 42: 4438, 43: 4440, 44: 4448, 45: 4462, 46: 4469, 47: 4475, 48: 7940, 49: 7946, 50: 7953, 51: 7967, 52: 7975, 53: 7977, 54: 7986, 55: 7996, 56: 8003, 57: 8013, 58: 8022, 59: 8024, 60: 8032, 61: 8046, 62: 8053, 63: 8059, 64: 9988, 65: 9994, 66: 10001, 67: 10015, 68: 10023, 69: 10025, 70: 10034, 71: 10044, 72: 10051, 73: 10061, 74: 10070, 75: 10072, 76: 10080, 77: 10094, 78: 10101, 79: 10107, 80: 10500, 81: 10506, 82: 10513, 83: 10527, 84: 10535, 85: 10537, 86: 10546, 87: 10556, 88: 10563, 89: 10573, 90: 10582, 91: 10584, 92: 10592, 93: 10606, 94: 10613, 95: 10619, 96: 12804, 97: 1281

##### Copy above values into the HLS conifer notebook.

##### Sanity checking whther the ciphertexts are order-preserving

In [15]:
dict_values = list(ciphertext.values())
sorted_dict_values = sorted(dict_values)
 
# comparing sorted list with sub_list
res = sorted_dict_values == dict_values
     
# printing result
print("Are values in order : " + str(res))

Are values in order : True


#### Sanity check that encryption and decryptions is working correctly with S and P changed to identity.

In [4]:
import numpy
import sys
import io

G =numpy.array([[1,0,0,0,1,1,1],[0,1,0,0,0,1,1],[0,0,1,0,1,0,1],[0,0,0,1,1,1,0]])

H =numpy.array([[1,0,0,0,1,1,1],[0,1,0,1,0,1,1],[0,0,1,1,1,0,1]])

#S =numpy.array([[1,1,0,1],[1,0,0,1],[0,1,1,1],[1,1,0,0]])
S = numpy.identity(4, dtype = int)
#P =numpy.array([[0,1,0,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,0,0,1],[1,0,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,0,0,1,0],[0,0,0,0,1,0,0]])	
P = numpy.identity(7, dtype = int)

mapping=([4,1,5,2,7,6,3])
matrix = numpy.dot(S,G)%2
G_1 = numpy.dot(matrix,P)%2
message = [([0,0,0,0]), ([0,0,0,1]), ([0,0,1,0]), ([0,0,1,1]), ([0,1,0,0]), ([0,1,0,1]), ([0,1,1,0]), ([0,1,1,1]), 
           ([1,0,0,0]), ([1,0,0,1]), ([1,0,1,0]), ([1,0,1,1]), ([1,1,0,0]), ([1,1,0,1]), ([1,1,1,0]), ([1,1,1,1])]
e = ([0,0,0,0,1,0,0])
for message2 in message:
    e = ([0,0,0,0,1,0,0])
    print('Message2:\n',message2, 'In decimal format: ', int(''.join(map(str,message2)),2))
    res=numpy.dot(message2,G_1)%2
    cipher2 = numpy.add(res,e)%2
    print('\nCipher2:',cipher2, 'In decimal format: ', int(''.join(map(str,cipher2)),2))
    P_1=numpy.linalg.inv(P)%2
    y2_1 = numpy.dot(cipher2,P_1)%2
    syndrome = numpy.dot(H,numpy.transpose(cipher2))%2
    error = syndrome[0]+2*syndrome[1]+4*syndrome[2]
    error=mapping[int(error-1)]
    y2_1[error-1]=(y2_1[error-1]+1)%2
    S_1=numpy.linalg.inv(S)%2
    decipher = numpy.dot(y2_1[0:4],S_1)%2
    print ('\nDecipher:',decipher, 'In decimal format: ', int(''.join(map(str,[int(i) for i in decipher])),2))
    print('-------------------------------------')

Message2:
 [0, 0, 0, 0] In decimal format:  0

Cipher2: [0 0 0 0 1 0 0] In decimal format:  4

Decipher: [0. 0. 0. 0.] In decimal format:  0
-------------------------------------
Message2:
 [0, 0, 0, 1] In decimal format:  1

Cipher2: [0 0 0 1 0 1 0] In decimal format:  10

Decipher: [0. 0. 0. 1.] In decimal format:  1
-------------------------------------
Message2:
 [0, 0, 1, 0] In decimal format:  2

Cipher2: [0 0 1 0 0 0 1] In decimal format:  17

Decipher: [0. 0. 1. 0.] In decimal format:  2
-------------------------------------
Message2:
 [0, 0, 1, 1] In decimal format:  3

Cipher2: [0 0 1 1 1 1 1] In decimal format:  31

Decipher: [0. 0. 1. 1.] In decimal format:  3
-------------------------------------
Message2:
 [0, 1, 0, 0] In decimal format:  4

Cipher2: [0 1 0 0 1 1 1] In decimal format:  39

Decipher: [0. 1. 0. 0.] In decimal format:  4
-------------------------------------
Message2:
 [0, 1, 0, 1] In decimal format:  5

Cipher2: [0 1 0 1 0 0 1] In decimal format:  41

Decip

#### Testing for another message

In [5]:
import numpy
import sys
import io

G =numpy.array([[1,0,0,0,1,1,1],[0,1,0,0,0,1,1],[0,0,1,0,1,0,1],[0,0,0,1,1,1,0]])

H =numpy.array([[1,0,0,0,1,1,1],[0,1,0,1,0,1,1],[0,0,1,1,1,0,1]])

S =numpy.array([[1,1,0,1],[1,0,0,1],[0,1,1,1],[1,1,0,0]])
P =numpy.array([[0,1,0,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,0,0,1],[1,0,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,0,0,1,0],[0,0,0,0,1,0,0]])	
#P = numpy.identity(7, dtype = int)

mapping=([4,1,5,2,7,6,3])
matrix = numpy.dot(S,G)%2
G_1 = numpy.dot(matrix,P)%2


message2 = ([1,0,0,0])
e = ([0,0,0,0,0,0,0])

print('Message2:\n',message2, 'In decimal format: ', int(''.join(map(str,message2)),2))
print('G:\n',G)
print('S:\n',S)
print('P:\n',P)
print('Result:\n',G_1)

'''
if (len(sys.argv)>1):
        message=numpy.genfromtxt(io.StringIO(sys.argv[1]),delimiter=',')
'''

res=numpy.dot(message2,G_1)%2

cipher2 = numpy.add(res,e)%2

print('\nCipher2:',cipher2, 'In decimal format: ', int(''.join(map(str,cipher2)),2))

P_1=numpy.linalg.inv(P)%2

print('\nP^{-1}:\n',P_1)

y2_1 = numpy.dot(cipher2,P_1)%2

syndrome = numpy.dot(H,numpy.transpose(cipher2))%2

error = syndrome[0]+2*syndrome[1]+4*syndrome[2]
print("\nsyndrome\':",syndrome,error)
error=mapping[int(error-1)]
print ("Error position: ",error)
print ("y': ",y2_1)
y2_1[error-1]=(y2_1[error-1]+1)%2
print ("y' (corrected): ",y2_1)

S_1=numpy.linalg.inv(S)%2


print ('\nS^{-1}:\n',S_1)

# syn = ([1,0,0,0])

decipher = numpy.dot(y2_1[0:4],S_1)%2

print ('\nDecipher:',decipher, 'In decimal format: ', int(''.join(map(str,[int(i) for i in decipher])),2))

Message2:
 [1, 0, 0, 0] In decimal format:  8
G:
 [[1 0 0 0 1 1 1]
 [0 1 0 0 0 1 1]
 [0 0 1 0 1 0 1]
 [0 0 0 1 1 1 0]]
S:
 [[1 1 0 1]
 [1 0 0 1]
 [0 1 1 1]
 [1 1 0 0]]
P:
 [[0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0]]
Result:
 [[1 1 0 1 0 1 0]
 [1 1 0 0 1 0 0]
 [1 0 0 1 0 0 1]
 [0 1 1 1 0 0 0]]

Cipher2: [1 1 0 1 0 1 0] In decimal format:  106

P^{-1}:
 [[0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]

syndrome': [0 1 1] 6
Error position:  6
y':  [1. 1. 0. 1. 0. 1. 0.]
y' (corrected):  [1. 1. 0. 1. 0. 0. 0.]

S^{-1}:
 [[1. 1. 0. 1.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]
 [1. 0. 0. 1.]]

Decipher: [1. 0. 0. 0.] In decimal format:  8


#### Rough: Testing Homomorphic Addition

In [7]:
import numpy as np
print('Adding ciphers:')
cipher_add = [int(i) for i in  bin(int(''.join(map(str,cipher2)),2) + int(''.join(map(str,cipher1)),2))[2:]]
print('Result after cipher addition: ', cipher_add, '. In decimal format: ', int(''.join(map(str,cipher_add)),2))
P_1=numpy.linalg.inv(P)%2

print('\nP^{-1}:\n',P_1)

y_1 = numpy.dot(cipher_add,P_1)%2

syndrome = numpy.dot(H,numpy.transpose(cipher_add))%2

error = syndrome[0]+2*syndrome[1]+4*syndrome[2]
error=mapping[int(error-1)]
print ("y': ",y_1)
y_1[error-1]=(y_1[error-1]+1)%2
print ("y' (corrected): ",y_1)

S_1=numpy.linalg.inv(S)%2

print ('\nS^{-1}:\n',S_1)

# syn = ([1,0,0,0])

decipher = numpy.dot(y_1[0:4],S_1)%2

print ('\nDecipher:',decipher, 'In decimal format: ', int(''.join(map(str,[int(i) for i in decipher])),2))

print('Expected result: {} + {} = {}.'.format(int(''.join(map(str,message1)),2), int(''.join(map(str,message2)),2),  int(''.join(map(str,message1)),2) + int(''.join(map(str,message2)),2)))

Adding ciphers:
Result after cipher addition:  [1, 1, 1, 0, 0, 1, 0, 1] . In decimal format:  229

P^{-1}:
 [[0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]


ValueError: shapes (8,) and (7,7) not aligned: 8 (dim 0) != 7 (dim 0)